[package]
name = "tush"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8.9"
clap = { version = "4.6.6", features = ["derive", "env"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
enum_dispatch = "0.3"
figment = { version = "0.10.19", features = ["yaml"] }
http-body-util = "0.1.5"
hyper = { version = "1.11.1", features = ["client", "http1"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
libc = "0.2"
parking_lot = "0.12.5"
parse-size = "1.1.0"
petgraph = { version = "0.8", default-features = false, features = ["std"] }
ratatui = "0.30.2"
replace_with = "0.1.8"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
smallvec = { version = "1.16", features = ["serde"] }
smol_str = { version = "0.3.6", features = ["serde"] }
string-interner = "0.20.0"
thiserror = "2.0.20"
tokio = { version = "^1.52", features = ["full"] }
tokio-stream = "0.1.19"
tokio-util = "0.7"
unicode-width = "0.2.2"
